version: '3'
services:
  mysql-master:
    build:
      context: Backend
      dockerfile: Backend/Dockerfile
      target: master

  mysql-slave:
    build:
      context: Backend
      dockerfile: Backend/Dockerfile
      target: slave

  ceph-mon:
    image: ${CEPH_IMAGE}
    ports:
      - "7000:7000"
    environment:
      - CEPH_CONF=/etc/ceph.conf
      - MON_ADDRESS=${MON_ADDRESS}

  ceph-osd-1:
    image: ${CEPH_IMAGE}
    environment:
      - CEPH_CONF=/etc/ceph.conf
      - OSD_ID=1

  ceph-osd-2:
    image: ${CEPH_IMAGE}
    environment:
      - CEPH_CONF=/etc/ceph.conf
      - OSD_ID=2

  ceph-mgr:
    image: ${CEPH_IMAGE}
    ports:
      - "8000:8000"
    environment:
      - CEPH_CONF=/etc/ceph.conf

  ceph-rgw:
    image: ${CEPH_IMAGE}
    ports:
      - "7480:7480"
    environment:
      - CEPH_CONF=/etc/ceph.conf
      - RGW_NAME=rgw

  consul:
    image: consul:1.14
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit-server
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq