version: '3.8'

networks:
  db_network:
    ipam:
      config:
        - subnet: 172.21.0.0/16
  app_network:
    ipam:
      config:
        - subnet: 172.22.0.0/16

volumes:
  es_data:
  minio_data:

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"
    networks:
      app_network:
        ipv4_address: 172.22.0.16
    ulimits:
      memlock:
        soft: -1
        hard: -1
    user: elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "0.0.0.0:5601:5601"
    networks:
      app_network:
        ipv4_address: 172.22.0.17
    depends_on:
      - es

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=adminpassword
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    networks:
      app_network:
        ipv4_address: 172.22.0.18

  redis:
    image: redis:6.2-alpine
    command: redis-server --appendonly yes
    ports:
      - "0.0.0.0:6379:6379"
    networks:
      db_network:
        ipv4_address: 172.21.0.4

  minio-server:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio:/data
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9001:9001"
    networks:
      app_network:
        ipv4_address: 172.22.0.20
    command: server /data --console-address ":9001"

  consul:
    image: consul:1.9
    ports:
      - "0.0.0.0:8500:8500"
      - "0.0.0.0:8600:8600/udp"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    networks:
      app_network:
        ipv4_address: 172.22.0.21

  pd:
    image: pingcap/pd:latest
    ports:
      - "0.0.0.0:2379:2379"
    volumes:
      - ./config/pd.toml:/pd.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --name=pd
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd:2379
      - --advertise-peer-urls=http://pd:2380
      - --initial-cluster=pd=http://pd:2380
      - --data-dir=/data/pd
      - --config=/pd.toml
      - --log-file=/logs/pd.log
    restart: on-failure

  tikv:
    image: pingcap/tikv:latest
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --data-dir=/data/tikv
      - --pd=pd:2379
      - --config=/tikv.toml
      - --log-file=/logs/tikv.log
    ports:
      - "0.0.0.0:20160:20160"
    depends_on:
      - "pd"
    restart: on-failure

  tidb:
    image: pingcap/tidb:latest
    ports:
      - "0.0.0.0:4000:4000"
      - "0.0.0.0:10080:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --store=tikv
      - --path=pd:2379
      - --config=/tidb.toml
      - --log-file=/logs/tidb.log
      - --advertise-address=tidb
    depends_on:
      - "tikv"
    restart: on-failure